### ISSUE TITLE
Direct links to pages return a 404 error

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/stats.jenkins.io#118]
### Reproduction steps

1. Open https://new.stats.jenkins.io/statistics

### Expected Results

"Statistics in detail" page is displayed.

### Actual Results

A 404 error is returned.

From https://stackoverflow.com/a/43557288/4074148:
> When your react.js app loads, the routes are handled on the frontend by the react-router. Say for example you are at https://new.stats.jenkins.io. Then on the page you navigate to https://new.stats.jenkins.io/statistics. This route change is handled in the browser itself.
> Now when you refresh or open the url https://new.stats.jenkins.io/statistics in the a new tab, the request goes to your nginx where the particular route does not exist and hence you get 404.

**Comment by lemeurherve** [comment]
>
> https://new.stats.jenkins.io/statistics still returns a 404 error for me,
same for you?

**Comment by lemeurherve** [comment]
I think a proper fix would be to add a try_files to https://github.com/jenkins-infra/helm-charts/blob/99677ae1599f87d1ffe0b461ebff0ed80f04cfa0/charts/nginx-website/templates/nginx-configmap.yaml with something like https://stackoverflow.com/a/43557288/4074148.

Note: In PTO for two weeks I probably won't have time to take a closer look at it before mid-August.

**Comment by krisstern** [comment]
Yup, the fix worked on the preview but not on https://new.stats.jenkins.io/statistics

**Comment by shlomomdahan** [comment]
Doesn't it take some time for new.stats.jenkins.io to reflect the most recent updates?

Could that be the issue or it's just not a proper fix?

**Comment by shlomomdahan** [comment]
Are the preview and the deployment both on Netlify?

Or is the deployment hosted somewhere else?

I think netlify uses ngnix server

**Comment by HagegeR** [comment]
I've seen that from the latest deployment (in a PR) we can already access directly links:
https://deploy-preview-123--stats-jenkins-io.netlify.app/plugin-trends

**Comment by lemeurherve** [comment]
Previews are served by Netlify which has its own server configuration.

Production served by a nginx server hosted on our cluster is cached by
Fastly.

This is this nginx server configuration that needs to be updated.

**Comment by shlomomdahan** [comment]
@lemeurherve 

should I make a PR on :

- https://github.com/jenkins-infra/helm-charts/blob/99677ae1599f87d1ffe0b461ebff0ed80f04cfa0/charts/nginx-website/templates/nginx-configmap.yaml ?

Or should we have a ```nginx.conf``` file in this repo?

Proposed code would be:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-website.fullname" . }}
  labels: {{ include "nginx-website.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;
        try_files $uri /index.html;
      }
    }
```

**Comment by lemeurherveCB** [comment]
This issue has been resolved with https://github.com/jenkins-infra/kubernetes-management/pull/5595.

**Comment by krisstern** [comment]
Thanks @lemeurherveCB
