### ISSUE TITLE
Statistics in Detail's Plugin page reloaded once on load

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#134]
### Reproduction steps

1. If I go to the preview site at https://new.stats.jenkins.io/
2. Then click on "Statistics in Detail" button
3. Sometimes the plot would load twice on load

### Expected Results

There is no loading twice of the same data

### Actual Results

There is a loading twice of the same data

**Comment by shlomomdahan** [comment]
@krisstern 
Can you please provide more details? I am having trouble reproducing the issue.

Thanks

**Comment by krisstern** [comment]
Cannot reproduce locally
