### ISSUE TITLE
Use standard header

### ISSUE THREAD

**Issue by timja** [jenkins-infra/stats.jenkins.io#14]
### What feature do you want to see added?

All jenkins.io sites should be using the standard header, see https://www.jenkins.io/

docs: https://jenkins-io-components.netlify.app/?path=/docs/example-introduction--docs

Currently:
<img width="1440" alt="image" src="https://github.com/jenkins-infra/stats.jenkins.io/assets/21194782/7cc283b0-47f9-4f05-9fe3-c12ac106e6cb">

Expected something like:
<img width="1437" alt="image" src="https://github.com/jenkins-infra/stats.jenkins.io/assets/21194782/b8a89bd0-58db-4626-b850-4d6eb33075ef">

**Comment by shlomomdahan** [comment]
@timja 

I have been trying to incorporate the header/footer Jenkins components for the new site but I can't seem to figure out how to import them. I read through the link provided and tried looking at some of the other Jenkins sites but can't find how they should be imported/used. 

Any guidance would be appreciated. Thank you

**Comment by shlomomdahan** [comment]
PR submitted for this issue:

ref: https://github.com/jenkins-infra/stats.jenkins.io/pull/16
