### ISSUE TITLE
Fix Overall Plugin Trends plot flickering on load issue

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#187]
### Reproduction steps

1. Go to https://stats.jenkins.io/
2. Click on "Statistics in Detail" button
3. Sometimes on first load the plot would flicker

### Expected Results

No flickering of plot on load. 

### Actual Results

There is flickering of plot on load.

**Comment by suzitsam** [comment]
I would like to work on this.

**Comment by afrinashar** [comment]
I would like to work on this.

**Comment by krisstern** [comment]
Hi @afrinashar someone has already volunteered to work on this within the last 7 days. You should wait until the 7-day limit is up to see if there will be no PR submitted before working on this.

**Comment by afrinashar** [comment]
Thank you for your  response

**Comment by UditNayak** [comment]
Hi @krisstern,

I tried to reproduce the issue on my local system (Windows WSL) using a Chrome browser. However, I’m having difficulty understanding what you mean by "flickering of the plot on load."

I noticed that whenever I click on the triple bar icon, the statistic data is reloaded. Is this what you are referring to as flickering?

If possible, could you provide more insights or a short video demonstrating the issue? It would be really helpful!

Thank you!

https://github.com/user-attachments/assets/3cb14fdb-b247-46df-affa-98f910f573f4

**Comment by krisstern** [comment]
Hi @UditNayak as I have indicated it does not happen all the time (hence the use of the word "sometimes"), so one part of the issue is to find out when that does happen. In the video you showed I do not see anything wrong, but I do see the flickering happening occasionally on my personal laptop's Chrome browser. 

Also, please wait until the others who have indicated their interest before you take their turn(s) before starting work on the issue, if you intend to.
