### ISSUE TITLE
Fix favicon aspect ratio issue

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#188]
### Reproduction steps

Go to the tab of [stats.jenkins.io](https://stats.jenkins.io/) to observe the aspect ratio compared to that of https://www.jenkins.io/

### Expected Results

Favicon to look like the one in https://www.jenkins.io/

### Actual Results

Now our favicon looks kind of fat with a different favicon image

**Comment by 720Florian** [comment]
I work in this issue

**Comment by krisstern** [comment]
Completed via #189
