### ISSUE TITLE
https://stats.jenkins.io/plugin-trends does not list any plugins whose name starts with `n`…`z`

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/stats.jenkins.io#192]
### Service(s)

stats.jenkins.io

### Summary

See title

### Reproduction steps

1. Go to https://stats.jenkins.io/plugin-trends
2. Jump to page 19.
3. Go back to page 18.

Observe lower-case plugin IDs end in the `m`s. Filtering by plugin IDs not listed also doesn't work.

Also, case-sensitive sort makes no sense here.

**Comment by daniel-beck** [comment]
@shlomomdahan Thanks for pointing out that you're not experiencing this problem, that's something I've not been aware of.

It seems this problem is caused by AdBlock Plus Premium, specifically the feature

> Block more distractions  
> Block floating videos, newsletter pop-ups, survey requests and site notifications. 

Looking at the error console, it does not like the file `https://stats.jenkins.io/assets/notification.stats-Bd35kmm8.json`, which is being blocked.

The block list is https://easylist-downloads.adblockplus.org/adblock_premium.txt and this rule stands out to me as a likely culprit:

    /notification.*.js$domain=~qudosbank.com.au|~myhealth.va.gov|~costco.ca|~costco.com

Those domains are exclusions, i.e., match unless on those domains. This looks like a pattern prone to false positives.

----

If we expect just me to be affected, that's fine and we can close this.

If we expect this to affect more people, perhaps a small change to filenames, e.g., adding a `plugin-` prefix, might do it?

A possible related improvement might be to make retrieval code more robust, so that a failure to retrieve one of the files does not cause the page to stop loading others, which seems to be the case at the moment (but unsure).

**Comment by krisstern** [comment]
Hi @daniel-beck let me look into this and follow this up soon!

**Comment by shlomomdahan** [comment]
Hi @daniel-beck @krisstern 

I just opened a PR #197 for this issue. 

I went with the third approach you suggested, namely, improving the robustness and error handling of the hook so that one failure will not affect the rest of the plugins retrieval. 

Would you be able to test this locally to see if it fixes the issue since I can't reproduce it myself?

Thank you
