### ISSUE TITLE
Sort year by descending order instead of ascending order in 

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#194]
### What feature do you want to see added?

For the "Monthyly Analysis" section, we would like to sort the years in a descending order instead of an ascending one:

<img width="1488" alt="Screenshot 2024-10-09 at 4 39 40 PM" src="https://github.com/user-attachments/assets/02033448-57f5-4e8b-97d6-57c0083f913c">

### Upstream changes

N/A

**Comment by SufyaanKhateeb** [comment]
I can work on this.

**Comment by krisstern** [comment]
Thanks @SufyaanKhateeb for your interest! 

You now have about 7 days to submit a PR before we allow someone else to contribute to the issue.
