### ISSUE TITLE
Add instructions how to build the website in the README

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/stats.jenkins.io#2]
### Describe your use-case which is not covered by existing documentation.

There is no instruction how to locally build the website in the README.

**Comment by shlomomdahan** [comment]
@lemeurherve 
I added some helpful instructions of the readme to get started with local development.

ref: https://github.com/jenkins-infra/stats.jenkins.io/pull/8

**Comment by lemeurherve** [comment]
Thanks!

Closed by https://github.com/jenkins-infra/stats.jenkins.io/pull/8

**Comment by HagegeR** [comment]
It is maybe just my opinion, but I believe the read-me should start by the purpose of the repo before getting into how to install/contribute etc.

**Comment by krisstern** [comment]
Hi @HagegeR, this project is a part of the ongoing GSoC 2024 and is not in production yet. There will be many additions to its documentation as the project progress. Currently it is still in its development phase.

**Comment by HagegeR** [comment]
I understand that @krisstern, but it might be something to revisit before finalizing the project

**Comment by lemeurherve** [comment]
For the record: https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2182602543

**Comment by lemeurherve** [comment]
Also: https://github.com/jenkinsci/plugin-modernizer-tool/pull/38
