### ISSUE TITLE
Sort Statistics in Detail > Monthly Analysis > All Data by Descending Order

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#200]
### What feature do you want to see added?

Currently we have for the Statistics in Detail > Monthly Analysis > All Data model data organised by month in ascending order, we would like to change this to sort by descending order instead in time.

Current view:
![image](https://github.com/user-attachments/assets/d78da334-ae46-4b23-aa76-8e811e475a41)

### Upstream changes

N/A

**Comment by krisstern** [comment]
Continued from https://github.com/jenkins-infra/docs.jenkins.io/issues/117

**Comment by Coffemin** [comment]
Is this assignment currently assigned to @divitttt? If this is a different issue can I work on this?

**Comment by krisstern** [comment]
Hi @Coffemin the issue was opened in the wrong repo eariler. I guess we will need to start a new queue so you may work on it over the next 7 days.

**Comment by KarruHarin** [comment]
I have completed the work and created a pull request. Could you please check it once, sir @krisstern?

**Comment by krisstern** [comment]
Hi @KarruHarin I will not review your PR as you are working on an issue already "assigned"
