### ISSUE TITLE
On Plugin Trends page, `Installation by Version` and `Installation by Version %` charts data is not loaded

### ISSUE THREAD

**Issue by Vandit1604** [jenkins-infra/stats.jenkins.io#215]
### Reproduction steps

1. Go to https://stats.jenkins.io/plugin-trends
2. Open any plugin trend

### Expected Results

"Installation by Versions" and "Installation by Version %" data charts not empty.

ran locally:
![image](https://github.com/user-attachments/assets/867146ef-0014-464c-96dd-4c1fae3025c9)

### Actual Results

"Installation by Versions" and "Installation by Version %" data charts are empty.

![image](https://github.com/user-attachments/assets/d6fbeb8b-1200-4926-aa78-b137b2fa4f98)

### Anything else?

Tested locally on https://github.com/jenkins-infra/stats.jenkins.io/commit/fdd73077ab8c7d82b309f56c3eda445b1b605115
![image](https://github.com/user-attachments/assets/a75fb279-36ce-450a-ae78-6a3d45c915e4)

The Data is not loaded only on the site but works properly locally.

Console output:
![image](https://github.com/user-attachments/assets/2d800571-8925-49f7-953b-3f1451677f8b)

The json file has empty object for installation for version and installation for version %

**Comment by krisstern** [comment]
Hi @Vandit1604 we have already opened an issue with helpdesk to try and resolve this issue.

**Comment by krisstern** [comment]
We cannot resolve this via any code changes here so I am closing this ticket for now

**Comment by Vandit1604** [comment]
@krisstern Can you share the helpdesk issue here. I couldn't find it previously.

**Comment by krisstern** [comment]
I will follow up on that you do not need to worry about it @Vandit1604

**Comment by PyvesB** [comment]
Hey there 👋🏻 The `installationsPerVersion` field is still empty, any news on this problem? It would be helpful to have visibility on what's going on on the helpdesk side.

**Comment by krisstern** [comment]
Hi @PyvesB this issue is closed. You are welcome to make a new issue to follow up.

**Comment by PyvesB** [comment]
How does duplicating an existing issue add value? If the problem wasn't resolved, this issue probably should not have been closed in the first place. Right now, it's harder for all external users to find out that this problem has already been reported or to get updates on it.

**Comment by krisstern** [comment]
Contrary to what has been claimed, I do not think increasing visibility will likely speed up the fixing of the issue. If you are interested please locate the issue yourself in the Jenkins Infra issues tracker, which is open to the public. And also if you are not a maintainer or stakeholder please do not comment on that issue unnecessarily to create noise. Thank you! 

Also, I am not going to re-open this issue for reasons I will not disclose here. But I do have my reasons why I am not going to do so.

**Comment by krisstern** [comment]
Also @PyvesB please respect the mainainer(s)'s decision on how they run a repo. It seems you have some very strong opinion(s) which may or may not be valid.

**Comment by PyvesB** [comment]
> I do not think increasing visibility will likely speed up the fixing of the issue

I agree, however, this was no my point.

> If you are interested please locate the issue yourself in the Jenkins Infra issues tracker, which is open to the public.

@Vandit1604 tried locating an external issue previously, and failed to do so. I'm assuming they

> And also if you are not a maintainer or stakeholder please do not comment on that issue unnecessarily to create noise

We rely on this API to provide badges on Shields.io, and they are partly broken because of this issue. The code for these badges were themselves contributed by folks who are maintainers on the Jenkins side, at least from what I can tell by glancing at their GitHub profiles. These badges are also featured in hundreds of repositories part of the Jenkins org, and I also found at least one reference to them in the Infra-specific org. This would match my definition of "stakeholder".

We're happy to host and maintain badges that were contributed by third-parties, but when the API of said third-parties stops working as expected and we're diligent enough to seek assistance but hit a wall, there's realistically not much more we can do. I'll go ahead and drop support for these badges on the Shields.io side. If ever this problem gets fixed, we'll be happy to consider re-adding support for them.

**Comment by krisstern** [comment]
Have you tried locating the issue but failed to do so

@Vandit1604 should have been able to do so but I am not sure why he couldn't, that may be a competency issue.

**Comment by krisstern** [comment]
Can you please continue the new issue I have just created? This issue is faulty and I have decided to close it to avoid further confusion. Really, please listen. Thanks!

**Comment by Vandit1604** [comment]
> Have you tried locating the issue but failed to do so?
> 
> @Vandit1604 should have been able to do so but I am not sure why he couldn't, that may be a competency issue.

I found your comment about a 'competency issue' demeaning. 
I believe we should focus on resolving the problem collaboratively rather than making personal remarks. Let's keep the discussion respectful and constructive moving forward. 😄 

Thanks.

**Comment by krisstern** [comment]
@Vandit1604 Thanks for your feedback, but this is not meant to be personal. You should have been able to locate it as you hae contributed to Jenkins before. I am trying to explain why your statement made no sense.

**Comment by krisstern** [comment]
Please @PyvesB @Vandit1604 this issue has been closed. Could you guys please follow up on the new issue if you would like to follow up?

**Comment by Vandit1604** [comment]
@krisstern Thanks for clarifying. I understand you didn’t intend for it to be personal, but framing it as a 'competency issue' can come across that way, regardless of intent or my previous contributions. I’d appreciate it if we keep the focus on the issue itself or constructive suggestions, as that fosters a more productive and respectful discussion. Let’s move forward and tackle the problem together. 🚀

**Comment by krisstern** [comment]
@Vandit1604 Thanks for your prompt reponse! I do not know why you could not find the issue, could you at least find where the Intra teams isssu tracker is, or did you have problems locating it? Or would you like us to focus back on the issue as you say and stop arguing because you feel offended?

**Comment by krisstern** [comment]
Thanks for the thumbs down emoji as a response @Vandit1604! But that would only make matters worse. Could you please "keep the focus on the issue itself or constructive suggestions, as that fosters a more productive and respectful discussion" like you have said?

**Comment by Vandit1604** [comment]
I'll be stepping down as the maintainer of this repository because voicing concerns is tagged as arguing by you.

Regards

**Comment by krisstern** [comment]
I have deliberately closed this issue exactly because of the conversation I anticipated we may have had here.

**Comment by krisstern** [comment]
> I'll be stepping down as the maintainer of this repository because voicing concerns is tagged as arguing by you.
> 
> Regards

That's realy a false accusation, and it is not fair to me. 

You have had a history of disrespecting and insulting me to be honest. Also, we are going to remove you as a maintainer anyways because of other competency issues we have seen previoulsy, nowo even more so now given your repeated behavioral issues.

**Comment by Vandit1604** [comment]
I’m disappointed by this response, as I have always tried to contribute to the Jenkins community in a positive way. While disagreements happen, I believe discussions should stay respectful and constructive, as per the Jenkins Code of Conduct.

If the organization has decided to remove me as a maintainer, I ask that the process be transparent, with clear reasons and evidence for the concerns raised. I’m open to discussing this further if needed, and will continue to focus on being professional and collaborative.

**Comment by krisstern** [comment]
Maybe I should bring in other co-maintainers like @gounthar to have a better assessment on this and to have some objective perspective besides the only two we have?

**Comment by krisstern** [comment]
We have already outlined the reasons why in the helpdesk issue you just commented on. I don't understand what you really want here: Are you stepping down voluntarily or are you okay with just triage rights? Because you did have a really poorly reviewed PR merged during Hacktoberfest which was faulty.

**Comment by krisstern** [comment]
We were lucky because that PR was not critial and also lucky because another contributor did created another PR to patch the issue.

**Comment by krisstern** [comment]
You should at least asked another maintainer like me to give it another review before you merged that PR, instead you rushed it and were very confident about it.

**Comment by krisstern** [comment]
You only DM me about it afterwards, which you should not have done. You should have pinged me in the PR to keep things transparent.

**Comment by Vandit1604** [comment]
Would you please point me to the Pull Request you are referring here?

**Comment by krisstern** [comment]
Please refer to the helpdesk issue I have created about downgrading your repo access rights for the evidence. I feel it is very convenient for you to just forget things like this when it is pretty serious for some of us.

**Comment by krisstern** [comment]
Seems also like you always needs other people'e help in locating issues / pull requests which is pretty interesting. I am not sure why but it can get very annoying on the receiving end.

**Comment by krisstern** [comment]
Also, thanks @PyvesB for not listening and insisting on commenting on this issue. This is exactly what I feared, but you wanted to have your way.
