### ISSUE TITLE
Automate Data Rendering and Eliminate Dependency on Submodule for infra-statistics

### ISSUE THREAD

**Issue by prachi-kCoder** [jenkins-infra/stats.jenkins.io#256]
The Jenkins-InfraWebsite currently relies on an old submodule to fetch and display monthly data. This issue aims to **automate the process of fetching, generating, and rendering data dynamically on the site, eliminating the need for the submodule dependency**

Feature Enhancements :- 
The task is to automate the rendering of Jenkins statistics, removing the dependency on the old submodule. Here's how each component will be handled:

1) **jenkins-stats (HTML, CSS, SVG):**
Convert static HTML, CSS, and SVG into dynamic React components.
Fetch and display data from .json files using React and ECharts for dynamic charts.

2) **plugin-installation-trend (.json files):**
Parse .json files to display plugin installation trends dynamically.
Implement automated updates to data monthly via scheduled processes.

3 ) **plugin-version (HTML & JS):**
Refactor static HTML/JS into React components for modularity and dynamic data rendering.
Use .json data to update plugin version matrix dynamically.

Tech Stack:

Frontend: React, TypeScript, ECharts, Chart.js
Automation: Scheduled updates (cron jobs or API calls)

**Comment by prachi-kCoder** [comment]
Kindly assign this issue to me , i have tried a lot to understand how all the data is being rendered .

**Comment by krisstern** [comment]
Hi @prachi-kCoder we have not planned for such a change, but thanks for the issue!

**Comment by krisstern** [comment]
This issue goes against what we have discussed during the actual GSoC project and is not what we are aiming for
