### ISSUE TITLE
Upgrade to React v19

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#275]
### What feature do you want to see added?

Would like to have the repo's React dependency to be upgraded from v18 to v19.

### Upstream changes

N/A

**Comment by saurabhraghuvanshii** [comment]
@krisstern if I am not wrong , we only need to change in Package.json  to upgrade from current version "react": "^18.3.1",
        "react-dom": "^18.3.1", to "^19.0.0"

**Comment by krisstern** [comment]
It is more than just updating dependencies or #254 would not be failing.

**Comment by krisstern** [comment]
Usually there is some upgrade guide to follow like this one: https://react.dev/blog/2024/04/25/react-19-upgrade-guide

**Comment by saurabhraghuvanshii** [comment]
@krisstern can i work on this?

**Comment by krisstern** [comment]
Sure, feel free to work on this issue
