### ISSUE TITLE
Improve X axis label zoom behavior

### ISSUE THREAD

**Issue by HagegeR** [jenkins-infra/stats.jenkins.io#36]
### What feature do you want to see added?

I understand that, at the default zoom level that looks at a span of multiple years the ticks would be each year.

But in cases of high zoom on the graph, and the tick update to be each month, the label should be updated to show year and month, or only month.

here is an example of the issue:
![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/20857346/b8b10208-a37c-469f-a41a-74275571fdf1)

**Comment by KitsuneKode** [comment]
@krisstern 
![image](https://github.com/user-attachments/assets/e1a19f61-70e3-4c71-a44b-7c1ed9a35f6e)

this issue can be closed

**Comment by krisstern** [comment]
Thanks @KitsuneKode for verifying the issue has already been resolved previously.
