### ISSUE TITLE
new.stats.jenkins.io not updated to latest version of repository

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#42]
I noticed that the [new.stats.jenkins.io](http://new.stats.jenkins.io/) link is not being updated to match the latest preview (https://github.com/jenkins-infra/stats.jenkins.io/deployments/preview). Is this normal? How often does the [new.stats.jenkins.io](http://new.stats.jenkins.io/) site get updated to match the latest version of the repository?

**Comment by lemeurherve** [comment]
Will be resolved as soon as the "CD" steps of https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2167717401 are completed.

Required steps before a functional CD process:
- "Add credentials to infra.ci.jenkins.io"
- "Add deployment step to the pipeline (publication from infra.ci.jenkins.io)"

I'm working on them, should be ready in a little while, I'll comment in this issue too when done.

**Comment by lemeurherve** [comment]
Reopening until CD process is validated.

**Comment by lemeurherve** [comment]
CD process validated 🙂 

Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4132#issuecomment-2181046436
