### ISSUE TITLE
We should have a button to redirect to landing page

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/stats.jenkins.io#52]
### What feature do you want to see added?

I would like to see a button to be added to each of the four pages so that the user can navigate back to the landing page easily. 

### Upstream changes

N/A

**Comment by shlomomdahan** [comment]
Hi @krisstern,
<img width="397" alt="Screenshot 2024-06-23 at 12 42 41 PM" src="https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/479b59ae-2901-40e2-b9c7-2604b5740b49">

Clicking on the 'Jenkins' text will navigate users back to the homepage.

**Comment by shlomomdahan** [comment]
As discussed, I will add breadcrumbs to the bottom of each page.

**Comment by krisstern** [comment]
Completed
