### ISSUE TITLE
Chart titles overlapping toolbox on smaller screens

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#59]
There is a responsiveness issue when viewing charts on smaller screens or mobile devices. The chart titles are not shrinking or wrapping properly, causing them to overlap with other parts of the charts, particularly the toolbox. This toolbox contains important buttons for resetting zoom and downloading data.

![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/64103471/3de0853c-7276-4acf-925c-bbf961841cd1)
 

@krisstern 

ref

- #57

**Comment by krisstern** [comment]
Completed
