### ISSUE TITLE
feat: add compare feature to stats-in-detail page

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#80]
ref: 

- #77 

@gounthar 
"Would it make sense to have a graph showing at the same time the monthly plugin usage, the total jobs, the monthly Jenkins installations, and the total nodes?"
@Vandit1604 
"Would it be possible to incorporate the overall trends on a single page, with a smaller size? Seeing all them on a single page can be easy to browse the overall statistics i.e. how many Jenkins installations were done, how many jobs were executed, total nodes over time."

Would you guys mind explaining in more detail what you'd like to see here? I'm not sure I fully understand what you mean in the above and I'd like a clear picture before I begin working on this feature.

Thank you!

**Comment by krisstern** [comment]
Actually, I am not sure if it makes sense to "have a graph showing at the same time the monthly plugin usage, the total jobs, the monthly Jenkins installations, and the total nodes", since it seems that they all scale differently. Also, if we were to show them on the same plot, we would have to have the same plotting area and the ability to toggle on or off each plot with a button.

**Comment by Vandit1604** [comment]
> "Would it be possible to incorporate the overall trends on a single page, with a smaller size? Seeing all them on a single page can be easy to browse the overall statistics i.e. how many Jenkins installations were done, how many jobs were executed, total nodes over time."

@shlomomdahan  We can have a single page where we have all 4 of these charts, something like this wireframe.
![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/107131545/764c0693-1f32-46fd-b403-7969ca945979)

So we can see how Jenkins is doing overall in one single place.
Other than that, I think Overall trends deserve a single dedicated page.

**Comment by krisstern** [comment]
> > "Would it be possible to incorporate the overall trends on a single page, with a smaller size? Seeing all them on a single page can be easy to browse the overall statistics i.e. how many Jenkins installations were done, how many jobs were executed, total nodes over time."
> 
> @shlomomdahan We can have a single page where we have all 4 of these charts, something like this wireframe. ![image](https://private-user-images.githubusercontent.com/107131545/346278913-764c0693-1f32-46fd-b403-7969ca945979.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNzY0MTcsIm5iZiI6MTcyMDI3NjExNywicGF0aCI6Ii8xMDcxMzE1NDUvMzQ2Mjc4OTEzLTc2NGMwNjkzLTFmMzItNDZmZC1iNDAzLTc5NjljYTk0NTk3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNlQxNDI4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzJiODYwMzU3ZTlmNjU3MWFkNzk2MGM1MTg3MWIyMjlkZDU2MzQ4OTdiMmY3MmZmMTk5ODZiOWEzOTcxODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sIajoiaXYHPK5KALput0o3_T_3yBdqQLWKOVJjx9bSs)
> 
> So we can see how Jenkins is doing overall in one single place. Other than that, I think Overall trends deserve a single dedicated page.

@Vandit1604 I don't think that is a good idea

**Comment by Vandit1604** [comment]
I would disagree. Currently, we have Monthly Analysis and Overall trends in a single page which makes it cluttered.

![image](https://github.com/jenkins-infra/stats.jenkins.io/assets/107131545/e7e55bf4-9c98-4956-bf26-6359a86c933b)

**Comment by krisstern** [comment]
@Vandit1604 I prefer what @gounthar has suggested, and not your design.

**Comment by krisstern** [comment]
@gounthar Would you mind providing more details of your proposal?

**Comment by krisstern** [comment]
If need be we do not change anything

**Comment by krisstern** [comment]
> Actually, I am not sure if it makes sense to "have a graph showing at the same time the monthly plugin usage, the total jobs, the monthly Jenkins installations, and the total nodes", since it seems that they all scale differently. Also, if we were to show them on the same plot, we would have to have the same plotting area and the ability to toggle on or off each plot with a button.

@Vandit1604 Also, this

**Comment by gounthar** [comment]
Thank you for your input. I appreciate your suggestions regarding the scales and graphs. Here are my thoughts and proposed improvements:

1. **Multiple Scales**: We would need at least two scales—one on the left and one on the right—to adequately represent the data from four graphs. This approach will allow for a more accurate comparison of trends.

2. **Data Representation**: While I don't have the exact numbers available, using two scales could maybe be sufficient to represent the four graphs effectively. This method would help us visualize potential correlations between the different trends.

3. **Clarity of Purpose**: To enhance the clarity of our objective, we could state it more explicitly: "The primary goal of this visualization is to identify and analyze potential correlations between these diverse trends."

4. **Legend and Labels**: To further improve clarity, we should ensure that each line or data set is clearly labeled and that a comprehensive legend is included. This addition will help readers easily distinguish between the different trends being compared.

5. **Color Scheme**: Consider using a color-blind friendly palette for the graph lines. This choice would make the visualization more accessible and inclusive.

6. **Annotations**: Where significant correlations or divergences occur, we could add brief annotations to draw attention to these points. This feature would aid in guiding the viewer's understanding of the data relationships.

By implementing these suggestions, I think we could create a more effective and user-friendly visualization that clearly communicates the relationships between the different trends (plugin use, controller installs, and so on).

**Comment by shlomomdahan** [comment]
As per our weekly call:

We will be shifting our focus to the Stats-In-Detail page. The plan is to create a new modal with a dropdown selector that allows users to choose 2 to 4 graphs to compare trends between important data.
