### ISSUE TITLE
website slow to load

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#87]
Occasionally the site will take anywhere from 10-60 seconds to load.

will open issue in https://github.com/jenkins-infra/helpdesk

ref:

- https://github.com/jenkins-infra/helpdesk/issues/4177

**Comment by shlomomdahan** [comment]
ref: 
- https://github.com/jenkins-infra/helpdesk/issues/4177

Speed has improved to 3-4 seconds load time for the site.

As mentioned in the above issue, we need to reduce asset size to <5mb

**Comment by gounthar** [comment]
Do we get the minified versions of the JS files before zipping them? 🤔

**Comment by shlomomdahan** [comment]
new PR ( build size appears <5mb! )

ref:
-https://github.com/jenkins-infra/stats.jenkins.io/pull/110
