### ISSUE TITLE
open issue in jenkins.io components to add link to this site (stats.jenkins.io)

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#88]
currently, the jenkins.io header component does have a static link back to our website.

**Comment by shlomomdahan** [comment]
Hi @krisstern,

Can you please explain in more detail what we are going for here? Do you want to see one of the drop-downs on the navbar with a link to new.stats.jenkins.io?

I didn't fully catch what you were trying to show during the weekly call.

Thank you!

**Comment by krisstern** [comment]
Hi @shlomomdahan,

Sure! So basically we will need to first open an issue at https://github.com/jenkins-infra/jenkins-io-components to discuss where is the best location to add a link to the stats.jenkins.io (the expected location of the revamped site), and then add a link to either the header / footer as agreed on.

**Comment by shlomomdahan** [comment]
PR has been opened in the jio repo to add link

- https://github.com/jenkins-infra/jenkins-io-components/pull/148
